### ISSUE TITLE
Division by zero on 01_Step_1.ipynb

### ISSUE THREAD

**Issue by xocd** [barbagroup/CFDPython#23]
Running 01_Step_1.ipynb I get a division by zero error.  The error goes away by setting
dx = 2.0/(nx-1) instead of dx = 2/(nx-1).  I am using anaconda Python 2.7.11 :: Anaconda 2.5.0 (x86_64).

Thanks!

**Comment by ncclementi** [comment]
Hey @xocd in case you haven't noticed it, all the notebooks were updated to work with Python 3 where dx = 2/(nx-1) ruturns a float. So if you update your Python to Python 3 it'll work with no problems!

Good luck!

**Comment by xocd** [comment]
Thanks!

Isidro (aka xocd)

On Mon, Feb 15, 2016 at 6:03 PM, ncclementi <notifications@github.com>
wrote:

> Hey @xocd <https://github.com/xocd> in case you haven't noticed it, all
> the notebooks were updated to work with Python 3 where dx = 2/(nx-1)
> ruturns a float. So if you update your Python to Python 3 it'll work with
> no problems!
>
> Good luck!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/barbagroup/CFDPython/issues/23#issuecomment-184434235>
> .
>



-- 
Isidro

**Comment by franktoffel** [comment]
You can also add:
`from __future__ import division
`
to make your code work. But I would rather recommend use Python 3 (specially if you are learning now).

**Comment by xocd** [comment]
I have created an environment using python 3.5; using it just works.

Thanks!
xocd

**Comment by ncclementi** [comment]
Great! Then I'm going to close this issue!
