### ISSUE TITLE
Use of ipython widgets

### ISSUE THREAD

**Issue by psychemedia** [barbagroup/CFDPython#30]
Looking at one of the early notebooks, you have a call to action: *What do you observe about the evolution of the hat function under the non-linear convection equation? What happens when you change the numerical parameters and run again?*

I wondered if you had considered making an interactive out of this using `ipywidgets`? (Or maybe you did and discounted it because it can detract from purposeful exploration and engagement with the code in favour of letting students just play with the interactive shiny bits?!)

**Comment by gforsyth** [comment]
Hey @psychemedia -- `ipywidgets` would be a great enhancement to the lesson! When we wrote these in the first place, the widgets were in their infancy but they've come a long way since.

**Comment by psychemedia** [comment]
(V impressed by the materials... I may well have to work though your course *as a course* as well as seeing how you go about using the notebooks for instructional purposes!)

**Comment by gforsyth** [comment]
Please do! You can also take a look at [barbagroup/AeroPython](https://github.com/barbagroup/AeroPython) and [numerical-mooc/numerical-mooc](https://github.com/numerical-mooc/numerical-mooc) for two of our other offerings.
