### ISSUE TITLE
Step4: Error in periodic boundary condition ?

### ISSUE THREAD

**Issue by jazzalin** [barbagroup/CFDPython#32]
Hey, when handling the periodic boundary conditions in Step 4, after the second for loop of code snippet #10, you have
`u[-1] = un[-1] - un[-1] * dt / dx * (un[-1] - un[-2]) + nu * dt / dx**2 * (un[0] - 2 * un[-1] + un[-2])`
where in the last set of parentheses you obtained `un[i + 1]` = `un[-1 + 1]` = `un[0]`.

Given the boundary u(0) = u(2*pi), shouldn't it be `un[i + 1]` = `un[0 + 1]` = `un[1]` instead of `un[0]` ?

Thanks in advance!

**Comment by gforsyth** [comment]
Hey @jazzalin -- sorry for the _long_ delay in getting to this.

Yes, you are correct, it should be `un[1]`. Alternatively, since they are the same point, as you noted, we could just set `u[-1] = u[0]` after applying the first boundary condition.

Would you like to PR in the changes?

Thanks!

**Comment by jazzalin** [comment]
No worries, thanks for getting back to me.
Yeah that also works! Created a PR.

Thanks

**Comment by gforsyth** [comment]
Resolved in #33
