### ISSUE TITLE
Error in equation for calculating u in linear convection

### ISSUE THREAD

**Issue by Anirudh257** [barbagroup/CFDPython#38]
In linear convection's equation:

`u = numpy.ones(nx)

u[int(.5/dx):int(1 / dx + 1)] = 2`

Line 2 will give a zero error.

**Comment by PKHG** [comment]
Hallo, you always should give a precise context ;-)
[code]
import numpy
nx = 14
u = numpy.ones(nx)
dx =0.2
u[int(.5/dx):int(1 / dx + 1)] = 2 
u
[/code]
gives: array([ 1.,  1.,  2.,  2.,  2.,  2.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

**Comment by mesnardo** [comment]
Hi @Anirudh257 

I suspect you are using Python 2, which has a different behavior than Python 3 when it comes to division.
When using Python 2, the problem comes from the cell above the one you mention where we compute the grid cell width `dx`.
With Python 2, division between two integers returns an integer and thus `dx = 2 / (nx - 1)` will return `0`.
With Python 3, it will return a float, i.e. `0.05`.

**Comment by mesnardo** [comment]
```python
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> nx = 41
>>> dx = 2 / (nx - 1)
>>> dx
0.05
>>> u = numpy.ones(nx)
>>> u[int(0.5 / dx): int(1 / dx + 1)] = 2
>>> u
array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.])
```

**Comment by mesnardo** [comment]
```python
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> nx = 41
>>> dx = 2 / (nx - 1)
>>> dx
0
>>> u = numpy.ones(nx)
>>> u[int(0.5 / dx): int(1 / dx + 1)] = 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: float division by zero
```

**Comment by PKHG** [comment]
with Python 2 you need e.g. use this  dx = 2.0/(nx-1) to force a decimal ;-

**Comment by gforsyth** [comment]
We explicitly do not support Python 2

**Comment by Anirudh257** [comment]
Sorry, @mesnardo I am a beginner on Github and this will never repeat again. The issue will be resolved on importing the future division method from Python 3. It has been pointed out above. I am closing this issue.
