### ISSUE TITLE
Equations in Step11 got messed up. 

### ISSUE THREAD

**Issue by merula89** [barbagroup/CFDPython#40]
Correctly displaying at Step12 -> copy from there where applicable. 
![grafik](https://user-images.githubusercontent.com/9959248/38766158-5d762226-3fce-11e8-8986-dfae7e8acb43.png)

**Comment by mesnardo** [comment]
Thank you @merula89 !
PR #41 will fix this issue.

**Comment by c0smas** [comment]
The problem is still there.  And may be someone answere, wherefrom the 1/delta(t)*div(U) term is appearing in Poisson eq? In previous steps was shown that div(U) = 0 .... just don't get it
