### ISSUE TITLE
11 step, d(div(U))/dt term 

### ISSUE THREAD

**Issue by c0smas** [barbagroup/CFDPython#56]
Hello, please someone answere me, wherefrom the 1/delta(t)*div(U) term is appearing in Poisson eq? In previous steps was used that div(U) = 0 .... just don't get it

**Comment by gforsyth** [comment]
Hi @c0smas -- you can check out the following video for some more context on the pressure poisson equation.  The explanation about the PPE starts at 18:40 but you might want to watch the whole video for more context about how it fits in.

https://youtu.be/ZjfxA3qq2Lg?t=18m40s

**Comment by c0smas** [comment]
Yes, I got it. Thank you!
