### ISSUE TITLE
No pressure gradient in step 12?

### ISSUE THREAD

**Issue by Beramos** [barbagroup/CFDPython#59]
If you plot the pressure profile after convergence of the Navier-Stokes equations coupled with the pressure-poisson equation there is no pressure gradient, is this an artifact of the periodic boundary conditions?

The pressure field does not change at all during iteration...

**Comment by piyueh** [comment]
According to the ***Learn more*** section in that notebook, what we solve is the pressure perturbation, not the pressure itself. The pressure itself in fully-developed pipe flow is not constant and has a constant gradient. But the pressure perturbation is a constant in fully-developed laminar pipe flow.

**Comment by Beramos** [comment]
Alright thank you. I did not think to check the learn more section
