### ISSUE TITLE
definition of L1 norm on Step 9: 2D Laplace Equation

### ISSUE THREAD

**Issue by bharath-kamath705** [barbagroup/CFDPython#69]
According to the link below, the L1 norm of a matrix is calculated by summing up absolute values in each column, and then taking the maximum
https://en.wikipedia.org/wiki/Matrix_norm

The notebook for Step 9 calculates the norm by summing up the absolute values of all the elements in the matrix. Also the link provided to read up further on the L1 norm leads to the wiki page for L1 norm of a vector (which I understand is different from the L1 norm of a matrix)

**Comment by mesnardo** [comment]
Hi @bharath-kamath705!
Step 9 of CFDPython solves the Laplace equation in a two-dimensional domain.
Numerically speaking, the variable `p` is the solution vector of the Laplace equation.
In this notebook, we use a 2D NumPy array to represent the solution vector, as it is easier to conceptualize the two-dimensional discretization and to visualize (with Matplotlib) the solution in the two-dimensional domain.
We can think of the variable `p` as a sequence of 1D arrays, where each array represents the solution along an horizontal gridline (starting from the bottom of the domain, up to the top).
Thus, using the definition of the L1-norm for a vector is appropriate here.

@labarba: To avoid the confusion, I think we should replace (in the notebook) "matrix" by "2D array" when talking about the variable `p`.

**Comment by bharath-kamath705** [comment]
Thanks for clarifying :)
