### ISSUE TITLE
change license note to indicate MIT for code

### ISSUE THREAD

**Issue by labarba** [barbagroup/CFDPython#9]
CC-BY only applies to text and image content. For code, we need to use an open-source code license (MIT license is our preference).

**Comment by ahmadia** [comment]
I think it's already clear: https://github.com/barbagroup/CFDPython/blob/master/LICENSE

**Comment by labarba** [comment]
The copyright note on each IPython Notebook still says CC-BY for text and code. We need some vim find-and-replace magic. :-)

**Comment by ahmadia** [comment]
ahh, got it.
